[profile.default]
contracts       = 'contracts'    # The contract directory
test            = 'tests'        # The test directory
libs            = ['modules']    # A list of library directories
solc_version    = '0.8.7'        # Override for the solc version (setting this ignores `auto_detect_solc`)
optimizer       = true           # Enable or disable the solc optimizer
optimizer_runs  = 200            # The number of optimizer runs
verbosity       = 3              # The verbosity of tests
block_timestamp = 1_622_400_000  # Timestamp for tests (non-zero)

[profile.deep]
fuzz_runs = 1000

[profile.super_deep]
fuzz_runs = 50000
